steps:
  # Access the service account secret
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'access-secret'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching service account..."
        gcloud secrets versions access latest --secret=${_SVC_ACCOUNT_JSON} > credentials.json

  # Fetch the .env secret
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'access-env'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Fetching .env file..."
        gcloud secrets versions access latest --secret=${_ENV_SECRET_NAME} > .env

  # Activate service account
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'use-service-account'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth activate-service-account --key-file=credentials.json

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_AUTO_TAG}'
      - '--build-arg'
      - 'GOOGLE_APPLICATION_CREDENTIALS=credentials.json'
      - '-f'
      - '${_DOCKERFILE}'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_AUTO_TAG}'

  # Deploy main API service to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/${_PROJECT_ID}/${_IMAGE_NAME}:${_AUTO_TAG}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'

  # Optional: Direct traffic to the latest deployed revision
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'services'
      - 'update-traffic'
      - '${_SERVICE_NAME}'
      - '--to-latest'
      - '--region'
      - 'us-central1'

substitutions:
  _PROJECT_ID: 'mathongo-assignment-466918'
  _IMAGE_NAME: 'mathongo-backend'
  _AUTO_TAG: '1.0.0'
  _DOCKERFILE: 'prod.Dockerfile'
  _SERVICE_NAME: 'mathongo-assignment-466918-api'
  _SVC_ACCOUNT_JSON: 'credentials'
  _ENV_SECRET_NAME: 'env-file'
